default: &default
  dispatchers:
    - polling_interval: 1
      batch_size: 500
  workers:
    - queues: "*"
      threads: 3
      processes: <%= ENV.fetch("JOB_CONCURRENCY", 1) %>
      polling_interval: 0.1

development:
  <<: *default
  database: teamchat_queue_development

test:
  <<: *default
  database: teamchat_queue_test

production:
  <<: *default
  database: teamchat_queue_production
